In [4]:
import pandas as pd
import numpy as np 
import seaborn as sns

In [2]:
penguins = sns.load_dataset("penguins")
penguins.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [ ]:
# One hot encoding for species

penguinsohe = penguins.copy()


penguins_encoded = pd.get_dummies(
    penguinsohe,
    columns = ['species'],
    drop_first = True
    # drops the first catagory column
    # only one column will be enough to know about both the catagories
)

# kind of redundant to keep all the catagory columns

penguins_encoded.sample(5)


island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
249  Biscoe            50.0           15.3              220.0       5550.0   
202   Dream            48.1           16.4              199.0       3325.0   
23   Biscoe            38.2           18.1              185.0       3950.0   
283  Biscoe            54.3           15.7              231.0       5650.0   
343  Biscoe            49.9           16.1              213.0       5400.0   

        sex  species_Chinstrap  species_Gentoo  
249    Male              False            True  
202  Female               True           False  
23     Male              False           False  
283    Male              False            True  
343    Male              False            True

In [27]:
# sklearn onehotencoder

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)

penguins_oh_encoded = ohe.fit_transform(penguinsohe[['species']])
print(penguins_oh_encoded)

df= pd.DataFrame(penguins_oh_encoded)
df


penguinsohe[['adelie_ohe','chinstrap_ohe','gentoo_ohe']] = penguins_oh_encoded
penguinsohe.sample(5)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
255  Gentoo  Biscoe            48.4           16.3              220.0   
325  Gentoo  Biscoe            46.8           16.1              215.0   
312  Gentoo  Biscoe            45.5           14.5              212.0   
293  Gentoo  Biscoe            46.5           14.8              217.0   
276  Gentoo  Biscoe            43.8           13.9              208.0   

     body_mass_g     sex  adelie_ohe  chinstrap_ohe  gentoo_ohe  
255       5400.0    Male         0.0            0.0         1.0  
325       5500.0    Male         0.0            0.0         1.0  
312       4750.0  Female         0.0            0.0         1.0  
293       5200.0  Female         0.0            0.0         1.0  
276       4300.0  Female         0.0            0.0         1.0