In [1]:
pip list

Package           Version
----------------- -----------
asttokens         3.0.1
colorama          0.4.6
comm              0.2.3
debugpy           1.8.17
decorator         5.2.1
exceptiongroup    1.3.1
executing         2.2.1
ipykernel         7.1.0
ipython           8.37.0
jedi              0.19.2
jupyter_client    8.6.3
jupyter_core      5.9.1
matplotlib-inline 0.2.1
nest-asyncio      1.6.0
numpy             2.2.6
packaging         25.0
parso             0.8.5
pip               21.2.3
platformdirs      4.5.0
prompt_toolkit    3.0.52
psutil            7.1.3
pure_eval         0.2.3
Pygments          2.19.2
python-dateutil   2.9.0.post0
pyzmq             27.1.0
setuptools        57.4.0
six               1.17.0
stack-data        0.6.3
tornado           6.5.2
traitlets         5.14.3
typing_extensions 4.15.0
wcwidth           0.2.14
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\devid\Desktop\Nexperts Academy\AI and ML for Beginners Repo\.venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [3]:
pip install pandas

  Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\devid\Desktop\Nexperts Academy\AI and ML for Beginners Repo\.venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [4]:
import pandas as pd

In [ ]:
#pip install numpy
 
import numpy as np

np.__version__ 

'2.2.6'

In [2]:
import array as ar

array1 = ar.array("i",[1,2,3,4,5,6])
type(array1)


array.array

In [10]:
arraynp = np.array([1,2,3,4,5,6,7,8,9,10])
# numpy lets us create nd arrays
type(arraynp)

array1D = np.array([1,2,3])
array1D
# 1 Dimensional Arrays - These are also called Vectors 
print("this is a ",array1D.ndim, "dimensional array")

this is a  1 dimensional array


In [13]:
array2D = np.array([[1,2,3],[1,2,3]])
print(array2D)
print("\nthis is a ",array2D.ndim, "dimensional array")

[[1 2 3]
 [1 2 3]]

this is a  2 dimensional array


In [ ]:
array3D = np.array([[[1,2,3],[1,2,3],[1,2,3]],
                    [[1,2,3],[1,2,3],[1,2,3]],
                    [[1,2,3],[1,2,3],[1,2,3]]])

In [ ]:
array3D = np.array([[[1],[2],[3]],
                    [[4],[5],[6]],
                    [[7],[8],[9]]])
print(array3D)
print("\nthis is a ",array3D.ndim, "dimensional array")

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]

this is a  3 dimensional array


In [27]:
# 1 2 3
# 4 5 6
# 7 8 9 

array19 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(array19,"\n\n",array19.ndim)



[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 2


In [ ]:
list1D = [1,2,3]

print(list1D*10)

print(array1D*10) # numpy arrays
# element wise operations
# broadcasting


# you take a scalar ( that only has a size, like integers)
# vectors - in physics things with magnitude and direction, 10km to East
# vectors - in maths, 

A = np.array([[1, 2, 3],
              [4, 5, 6]]) 

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [4, 5, 6]]) 

# array1D = np.array([1,2,3])

print(A.shape,B.shape)


# A * B

np.matmul(A,B) # matrix multiply

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[10 20 30]
(2, 3) (3, 3)


array([[21, 27, 33],
       [48, 63, 78]])

Numpy - calculations, 

using numpy other libraries have been made too 

Pandas built on top of numpy



In [ ]:
# create an arrays
import numpy as np

ai = np.arange(2,10000,2)
print(ai.dtype)

ai.shape # rows,columns
ai.size # number of elements
ai.ndim # how many dimensions
print(ai.dtype)

print(type(ai))


an = np.array(["idrees","samson","yaya","Hariz"])
print(an.dtype)
print(type(an))


a = np.array([4,"samson",4,"Hariz"])
print(a.dtype)
print(type(a))

# 1D array dimension, 
# 2D (1223,3434)

int64
int64
<class 'numpy.ndarray'>
<U6
<class 'numpy.ndarray'>
<U21
<class 'numpy.ndarray'>


In [37]:
line = np.linspace(0,1)
line

zeros = np.zeros((3,4))
print(zeros)

np.zeros_like(ai)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([0, 0, 0, ..., 0, 0, 0], shape=(4999,))

In [54]:
np.random.seed(11) 
# seed helps us set a starting point

# current time will always be different 

randSeq = np.random.rand(3,3) # rand ? using it to generate random values
randSeq

# there is no perfect way of creating a random value

# give me a random number - follows algorithms

arr10 = np.random.randint(0,100,size = 10)
print(arr10)

arr100 = np.random.randint(0,100, size = 100)
print(arr100)
rs = np.random.randint(1,100,(3,5))
rs

[ 4 34 12  1 74 37 84 81 91 24]
[17 67 70 43 64 79 96 23 27 70 89 10 57 27 44 14  7 55 79 64 40 27 95  5
 53 71 50 99 59  1  3  8 87 81 68 72 32 78 19 25 90 38 59 17 43 18 48 10
 47 32 44 40  8 68 33  1 95 75 34 72 19 96 84 50 82 59 72 38 39 34 31  4
 28 13 57 65 90 85 20 17 81 62  4 74 39 35 21 67 35 81  6 58 65 39 72  5
 37 91 93 50]


array([[86, 88, 11, 65, 50],
       [81, 88, 44, 13,  5],
       [35,  5, 35, 29, 88]], dtype=int32)

In [ ]:
# ar100    =  100 elements
# elementa   = 50 elements

elementa = arr100[0:50] # slicing
elementa[0]= 30

print(elementa[0])

print(arr100[0])
# changing the value of the new view, changes the previous array as well

# copying 

print(arr100)

print(elementa) # is just a viewww of arr100


# to create a new copy
elementcopy = arr100[0:50].copy()

elementcopy[0]= 75
print(elementcopy)
print(arr100)

elementcopy.size

r = elementcopy.reshape(10,5)
print(r)





30
30
[30 67 70 43 64 79 96 23 27 70 89 10 57 27 44 14  7 55 79 64 40 27 95  5
 53 71 50 99 59  1  3  8 87 81 68 72 32 78 19 25 90 38 59 17 43 18 48 10
 47 32 44 40  8 68 33  1 95 75 34 72 19 96 84 50 82 59 72 38 39 34 31  4
 28 13 57 65 90 85 20 17 81 62  4 74 39 35 21 67 35 81  6 58 65 39 72  5
 37 91 93 50]
[30 67 70 43 64 79 96 23 27 70 89 10 57 27 44 14  7 55 79 64 40 27 95  5
 53 71 50 99 59  1  3  8 87 81 68 72 32 78 19 25 90 38 59 17 43 18 48 10
 47 32]
[75 67 70 43 64 79 96 23 27 70 89 10 57 27 44 14  7 55 79 64 40 27 95  5
 53 71 50 99 59  1  3  8 87 81 68 72 32 78 19 25 90 38 59 17 43 18 48 10
 47 32]
[30 67 70 43 64 79 96 23 27 70 89 10 57 27 44 14  7 55 79 64 40 27 95  5
 53 71 50 99 59  1  3  8 87 81 68 72 32 78 19 25 90 38 59 17 43 18 48 10
 47 32 44 40  8 68 33  1 95 75 34 72 19 96 84 50 82 59 72 38 39 34 31  4
 28 13 57 65 90 85 20 17 81 62  4 74 39 35 21 67 35 81  6 58 65 39 72  5
 37 91 93 50]
[[75 67 70 43 64]
 [79 96 23 27 70]
 [89 10 57 27 44]
 [14  7 55 79 64]
 [

In [ ]:
print(r.sum())
print(r.min())
print(r.max())
print(r.sum(axis=0)) # columns wise
print(r.sum(axis= 1)) # row wise

2435
1
99
[551 383 633 404 464]
[319 295 227 219 220 280 247 226 247 155]
