<!--- Mohammad Idrees Bhat | Tech Skills Trainer | AI/ML Consultant --->

<div style="background-color: #add8e6; padding: 10px; height: 70px; border-radius: 15px;">
    <div style="font-family: 'Georgia', serif; font-size: 20px; padding: 10px; text-align: center; position: absolute; right: 20px;color: #000000ff;">
        Mohammad Idrees Bhat<br>
        <span style="font-family: 'Arial', sans-serif;font-size: 12px; color: #000000ff;">Tech Skills Trainer | AI/ML Consultant</span>
    </div>
</div>

<h1 style=" background-color: #002147; color: White; padding: 30px; text-align:center"> Python Libraries 1 - NumPy</h1>

<div style="background-color: lightgreen; color: black; padding: 10px;">
    <h1> 
</h1> </div>

<div style="background-color: grey; color: black; padding: 10px;">
    <h4><b>AGENDA</b> <p><p>
1. Python Libraries <p><p> 
2. NumPy <p>
3. Analyzing Data with NumPy <p>
4. - <p>

</h4> </div>

<h4> Skills Covered </h4>

- ...

<h4> Learning Outcomes </h4>

By the end of this lesson, students will be able to:

1. ..

<div style="background-color: lightgreen; color: black; padding: 4px;">
    <h4>1. Python Libraries 
</h4> </div>

In Python, a library is **a collection of modules** and **packages that provide pre-written code** to perform common tasks. Libraries allow developers to reuse code, streamline their workflows, and leverage existing functionality without having to reinvent the wheel. This makes programming faster, easier, and more efficient.

### Why Use Python Libraries?

1. **Code Reusability**: Libraries contain reusable code, which means you can use existing functions and classes instead of writing your own from scratch. This saves time and reduces errors.

2. **Simplified Development**: Libraries offer pre-built solutions to complex problems, making it easier for developers to implement functionalities without delving into the underlying details.

3. **Community Support**: Popular libraries are often well-documented and maintained by a community of developers. This support makes it easier to learn and troubleshoot issues.

4. **Enhanced Functionality**: Libraries expand Python's capabilities, allowing you to perform a wide range of tasks, from data analysis to web development and machine learning.

5. **Focus on Higher-Level Concepts**: By using libraries, developers can focus on high-level application logic rather than low-level implementation details.

<div style="background-color: lightblue; color: black; padding: 4px;">
    <h4>Common Python Libraries
</h4> </div>

### 1. **NumPy**
- **Purpose**: Provides support for numerical computations and handling multi-dimensional arrays.
- **Applications**: Used in scientific computing, data analysis, and machine learning.

### 2. **Pandas**
- **Purpose**: Offers data structures like Series and DataFrame for data manipulation and analysis.
- **Applications**: Ideal for data cleaning, transformation, and exploratory data analysis.

### 3. **Matplotlib**
- **Purpose**: A plotting library for creating static, animated, and interactive visualizations in Python.
- **Applications**: Used for data visualization and creating informative graphs and charts.

### 4. **Scikit-learn**
- **Purpose**: A machine learning library that provides simple and efficient tools for data mining and data analysis.
- **Applications**: Used for building predictive models, classification, regression, and clustering.

### 5. **TensorFlow and PyTorch**
- **Purpose**: Libraries for building and training neural networks and deep learning models.
- **Applications**: Widely used in machine learning and artificial intelligence projects.

### 6. **Flask and Django**
- **Purpose**: Web development frameworks for building web applications in Python.
- **Applications**: Flask is lightweight for smaller applications, while Django is a robust framework for larger, more complex projects.

## How to Install Python Libraries

Python libraries can be easily installed using `pip`, the package installer for Python. For example, to install NumPy and Pandas, you can run the following command in your terminal:

```bash
pip install numpy pandas


`pip install lib1 lib2 lib3 lib4`  

In [1]:
import math
print(math.sqrt(9))          # use with module name


import math as m
print(m.pi)                  # alias keeps code short

from math import sqrt, pi
print(sqrt(16), pi)          # import specific names

# from math import *        # works, but avoid (pollutes names)

3.0
3.141592653589793
4.0 3.141592653589793


### Let's Create a tiny library

In [2]:
# import mylib

print(mylib.APP_NAME)          # TinyTools
print(mylib.greet("Rehan"))    # Hello, Rehan! 👋
print(mylib.add(10, 5))        # 15
print(mylib.mood(3))           # Cheerful ☀️


NameError: name 'mylib' is not defined

In [ ]:
import mylib as mb

print(mb.greet("Team"))


In [ ]:
from mylib import greet, add

print(greet("World"))
print(add(7, 8))


Now check the library we actually created. the mpypkg

In [ ]:
from mypkg.tools import APP_NAME, greet, add, mood

<div style="background-color: lightgreen; color: black; padding: 4px;">
    <h4>2. NumPy
</h4> </div>

#### What is NumPy?

- NumPy (Numerical Python) is a library that:

- Gives us a fast array object called ndarray.

- Helps us do math on whole arrays at once (vectorized operations).

- Is used in almost every data science / machine learning project:

    - Storing data tables.

    - Doing statistics (mean, sum, std, etc.).

    - Matrix operations for ML.

In [ ]:
import numpy as np 

print(type(np.__version__))

In [ ]:
# If NumPy is not installed, run this in terminal:
# pip install numpy
# Import numpy and give it a short name 'np'

In [3]:
# Importing the libraries
import numpy as np
np.__version__

# Check the versions to confirm installation
print("NumPy version:", np.__version__)  # Output the version of NumPy

NumPy version: 1.26.4


NumPy is a powerful library for numerical computations in Python. It allows you to work with multi-dimensional arrays and provides functions to perform a variety of mathematical operations efficiently.

#### 1. Why Use NumPy?

- **Efficiency**: NumPy arrays are faster and more memory-efficient than Python lists.
- **Mathematical Operations**: Supports complex mathematical operations with arrays, including element-wise operations.
- **Multi-Dimensional Arrays**: NumPy allows you to work with arrays of any dimension (1D, 2D, 3D, etc.).



#### 2. Creating NumPy Arrays

The core feature of NumPy is the `ndarray` object. Let's start by creating an array:


In [4]:
import numpy as np  # make sure we have numpy imported

# Python list
py_list = [1, 2, 3, 4]

# Create a simple NumPy array from the Python list
arr_1d = np.array(py_list)

print("Python list:", py_list)
print("NumPy array:", arr_1d)
print("Type of arr_1d:", type(arr_1d))  # should be numpy.ndarray


Python list: [1, 2, 3, 4]
NumPy array: [1 2 3 4]
Type of arr_1d: <class 'numpy.ndarray'>


#### 1D, 2D, and 3D Arrays!

In [ ]:
# 1D array (like a simple list / vector)
a1 = np.array([1, 2, 3])
print("1D array (a1):", a1)
print("Number of dimensions:", a1.ndim)  # 1D

# 2D array (matrix: rows and columns)
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
print("\n2D array (a2):\n", a2)
print("Num1.26.4ber of dimensions:", a2.ndim)  # 2D

# 3D array (like multiple 2D matrices stacked)
a3 = np.array([[[1, 2], [3, 4]],
               [[5, 6], [7, 8]]])
print("\n3D array (a3):\n", a3)
print("Number of dimensions:", a3.ndim)  # 3D


1D array (a1): [1 2 3]
Number of dimensions: 1

2D array (a2):
 [[1 2 3]
 [4 5 6]]
Number of dimensions: 2

3D array (a3):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Number of dimensions: 3


#### NumPy array vs Python list

- NumPy lets us do math on all elements at once.

In [6]:
py_list = [1, 2, 3, 4]
np_arr = np.array(py_list)

# Multiply list by 10 (this repeats the list)
print("py_list * 10:", py_list * 10)

# Multiply NumPy array by 10 (this multiplies each element)
print("np_arr * 10:", np_arr * 10)


py_list * 10: [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
np_arr * 10: [10 20 30 40]


#### Some useful attributes

#### Array Properties

NumPy arrays have properties that provide useful information about the array's structure, such as the number of dimensions and shape.

### Key Points:
- **Dimensions (ndim)**: The number of axes (or dimensions) of the array. For example, a 1D array has one dimension, while a 2D array has two.

- **Shape**: The size of each dimension of the array, returned as a tuple. For example, a 2D array with 3 rows and 4 columns will have a shape of `(3, 4)`.


In [7]:
data = np.array([[10, 20, 30],
                 [40, 50, 60]])

print("Array:\n", data)

# Number of dimensions (1D, 2D, 3D, ...)
print("ndim:", data.ndim)

# Shape: (rows, columns)
print("shape:", data.shape)

# Total number of elements
print("size:", data.size)

# Data type of elements
print("dtype:", data.dtype)


Array:
 [[10 20 30]
 [40 50 60]]
ndim: 2
shape: (2, 3)
size: 6
dtype: int32


#### Creating arrays quickly

In [8]:
# Using `np.arange` (like Python `range`, but returns an array)

# Numbers from 0 to 9
a = np.arange(10)
print("np.arange(10):", a)

# Numbers from 0 to 9 with step 2
b = np.arange(0, 10, 2)
print("np.arange(0, 10, 2):", b)


np.arange(10): [0 1 2 3 4 5 6 7 8 9]
np.arange(0, 10, 2): [0 2 4 6 8]


In [9]:
# Splitting a 1D array into parts
arr = np.arange(10)
print("Original arr:", arr)

# Split into 3 (almost) equal parts
parts = np.array_split(arr, 3)

print("\nSplitted parts:")
for part in parts:
    print(part)


Original arr: [0 1 2 3 4 5 6 7 8 9]

Splitted parts:
[0 1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
# Using np.linspace (evenly spaced values)
# start, stop, num = 50
# 5 numbers between 0 and 1 (inclusive)
line = np.linspace(0, 1, 5)
print("np.linspace(0, 1, 5):", line)


In [ ]:
# Zeros, ones, full, identity

a = np.zeros((1,10))

b = np.zeros(10)


zeros = np.zeros((2, 3))       # 2 rows, 3 columns of 0s
ones  = np.ones((3, 2))        # 3 rows, 2 columns of 1s
full  = np.full((2, 2), 7)     # 2x2 filled with 7
identity   = np.eye(3)              # 3x3 identity matrix

print(a)
print(b)
print("zeros:\n", zeros)
print("\nones:\n", ones)
print("\nfull:\n", full)
print("\nidentity matrix:\n", identity)


In [ ]:
# Random Numbers

# Set a seed so results are reproducible
np.random.seed(42)

# Random floats in [0, 1), shape (2, 3)
rand_floats = np.random.rand(2, 3)
print("Random floats:\n", rand_floats)

# Random integers from 0 to 9, shape (2, 3)
rand_ints = np.random.randint(0, 10, (2, 3))
print("\nRandom integers:\n", rand_ints)


#### Indexing and slicing (2D arrays)

In [ ]:
A = np.array([[ 1,  2,  3],
              [ 4,  5,  6],
              [ 7,  8,  9]])

print("A:\n", A)

# Single element: A[row, column]
print("\nElement at (0, 0):", A[0, 0])  # 1
print("Element at (1, 2):", A[1, 2])    # 6

# Entire row (row 1)
print("\nRow 1:", A[1, :])

# Entire column (column 0)
print("Column 0:", A[:, 0])

# Submatrix (rows 0-1, columns 1-2)
sub = A[0:2, 1:3]
print("\nSubmatrix rows 0-1, cols 1-2:\n", sub)


In [13]:
# Views vs Copies (important!)

# Slices usually reference the same data (views), not a separate copy.

B = np.array([10, 20, 30, 40, 50])

# This is a view on B, not a copy
sub_view = B[1:4]
print("Original B:", B)
print("sub_view:", sub_view)

# Change sub_view - it also changes B
sub_view[0] = 999
print("\nAfter modifying sub_view[0] = 999")
print("B:", B)
print("sub_view:", sub_view)

# If we want an independent copy:
sub_copy = B[1:4].copy()
sub_copy[0] = -1
print("\nAfter modifying sub_copy[0] = -1")
print("B (unchanged now):", B)
print("sub_copy:", sub_copy)


Original B: [10 20 30 40 50]
sub_view: [20 30 40]

After modifying sub_view[0] = 999
B: [ 10 999  30  40  50]
sub_view: [999  30  40]

After modifying sub_copy[0] = -1
B (unchanged now): [ 10 999  30  40  50]
sub_copy: [-1 30 40]


#### Reshape, flatten, transpose

In [14]:
# Create an array from 0 to 11
arr = np.arange(12)
print("Original arr:", arr)

# Reshape into 3 rows, 4 columns
M = arr.reshape(3, 4)
print("\nReshaped to 3x4:\n", M)

# Flatten back to 1D (view when possible)
flat_view = M.ravel()
print("\nFlattened (ravel):", flat_view)

# Transpose (swap rows and columns)
print("\nTransposed M:\n", M.T)


Original arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened (ravel): [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed M:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


#### Element-wise operations & broadcasting

NumPy allows you to perform element-wise operations on arrays, making calculations easy and efficient.

### Key Points:
- **Element-wise operations** can be performed on arrays of the same shape.
- Operations can include **addition**, **subtraction**, **multiplication**, and **division**.

In [ ]:
# Example: Adding two arrays

import numpy as np  # Importing the NumPy library

# Creating two arrays of the same shape
arr1 = np.array([1, 2, 3])  # First array
arr2 = np.array([4, 5, 6])  # Second array

# Performing element-wise addition
arr_sum = arr1 + arr2  # Adds corresponding elements in arr1 and arr2
print("Element-wise Addition:", arr_sum)  # Output: [5 7 9]

# Performing element-wise subtraction
arr_diff = arr1 - arr2  # Subtracts corresponding elements in arr2 from arr1
print("Element-wise Subtraction:", arr_diff)  # Output: [-3 -3 -3]

# Performing element-wise multiplication
arr_product = arr1 * arr2  # Multiplies corresponding elements in arr1 and arr2
print("Element-wise Multiplication:", arr_product)  # Output: [4 10 18]

# Performing element-wise division
arr_quotient = arr1 / arr2  # Divides corresponding elements in arr1 by arr2
print("Element-wise Division:", arr_quotient)  # Output: [0.25 0.4 0.5]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print("x + y:", x + y)
print("x - y:", x - y)
print("x * y:", x * y)
print("y / x:", y / x)
print("x squared:", x ** 2)


x + y: [11 22 33]
x - y: [ -9 -18 -27]
x * y: [10 40 90]
y / x: [10. 10. 10.]
x squared: [1 4 9]


In [ ]:
# Broadcasting with scalars

arr = np.array([1, 2, 3])

# Scalar operations apply to every element
print("arr + 10:", arr + 10)
print("arr * 5:", arr * 5)

# Broadcasting in 2D

A = np.array([[1, 2, 3],
              [4, 5, 6]])

row = np.array([10, 20, 30])

# NumPy automatically "stretches" row to match A's shape
result = A + row

print("A:\n", A)
print("\nrow:", row)
print("\nA + row:\n", result)



In [ ]:
# Stacking and splitting arrays

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

# Stack vertically (one below another)
v_stack = np.vstack([a, b])
print("Vertical stack:\n", v_stack)

# Stack horizontally (side by side)
h_stack = np.hstack([a, b])
print("\nHorizontal stack:\n", h_stack)


#### Linear Algebra with NumPy

- Linear algebra is the mathematical backbone of machine learning.

- NumPy makes it easy to work with vectors and matrices.

In [ ]:
# Vectors and dot product

# Two 1D arrays (vectors)
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print("v1:", v1)
print("v2:", v2)

# Dot product = (1*4) + (2*5) + (3*6)
dot = np.dot(v1, v2)
print("Dot product:", dot)


v1: [1 2 3]
v2: [4 5 6]
Dot product: 32


In [16]:
# Matrix Multiplication

# 2x2 matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("A:\n", A)
print("\nB:\n", B)

# Matrix multiplication (A x B)
C1 = A @ B           # recommended operator
C2 = np.dot(A, B)    # function way
C3 = np.matmul(A, B) # another function

print("\nA @ B:\n", C1)
print("\nnp.dot(A, B):\n", C2)
print("\nnp.matmul(A, B):\n", C3)


A:
 [[1 2]
 [3 4]]

B:
 [[5 6]
 [7 8]]

A @ B:
 [[19 22]
 [43 50]]

np.dot(A, B):
 [[19 22]
 [43 50]]

np.matmul(A, B):
 [[19 22]
 [43 50]]


In [ ]:
# Transpose and Identity

M = np.array([[1, 2, 3],
              [4, 5, 6]])

print("M:\n", M)
print("\nTranspose of M:\n", M.T)

# Identity matrix of size 3 (already seen before)
I = np.eye(3)
print("\nIdentity matrix I:\n", I)


##### Solving a simple linear system Ax = b

- We want to solve the system:

- 3x + 1y = 9

- 1x + 2y = 8

In [17]:
A = np.array([[3, 1],
              [1, 2]])  # coefficient matrix
b = np.array([9, 8])     # right-hand side

# Solve for x
x = np.linalg.solve(A, b)

print("Solution x:", x)  # x contains [x_value, y_value]


Solution x: [2. 3.]


<div style="background-color: lightgreen; color: black; padding: 4px;">
    <h4>3. Analyzing Data with NumPy
</h4> </div>

#### Aggregations: sum, mean, min, max, std, var

In [ ]:


data = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("Data:\n", data)

# Aggregations on the whole array
print("\nSum:", data.sum())
print("Mean:", data.mean())
print("Min:", data.min())
print("Max:", data.max())
print("Std (standard deviation):", data.std())
print("Var (variance):", data.var())



Data:
 [[1 2 3]
 [4 5 6]]

Sum: 21
Mean: 3.5
Min: 1
Max: 6
Std (standard deviation): 1.707825127659933
Var (variance): 2.9166666666666665


#### Aggregations along an axis

- `axis=0` → operate column-wise (down the rows).

- `axis=1` → operate row-wise (across the columns).

In [ ]:
print("Column-wise sum (axis=0):", data.sum(axis=0))
print("Row-wise sum (axis=1):", data.sum(axis=1))

print("Column-wise mean:", data.mean(axis=0))
print("Row-wise mean:", data.mean(axis=1))


#### Boolean masking (filtering data)

- Used constantly to select rows/values that meet some condition.

In [24]:
scores = np.array([45, 72, 88, 30, 55, 90])

# Create a mask where condition is True/False
mask = scores >= 60

print("Scores:", scores)
print("Mask (scores >= 60):", mask)

# Use mask to pick only passing scores
passing_scores = scores[mask]
print("Passing scores:", passing_scores)

scores[scores >= 60]



Scores: [45 72 88 30 55 90]
Mask (scores >= 60): [False  True  True False False  True]
Passing scores: [72 88 90]


array([72, 88, 90])

In [ ]:
# More examples:

data = np.array([5, 12, 18, 7, 3, 25])

# Even numbers
even = data[data % 2 == 0]
print("Even numbers:", even)

# Numbers greater than 10
greater_10 = data[data > 10]
print("Numbers > 10:", greater_10)


In [25]:
# np.where for conditional values

# np.where(condition, value_if_true, value_if_false)

marks = np.array([40, 82, 60, 35, 95])

# Label as "Pass" or "Fail"
labels = np.where(marks >= 50, "Pass", "Fail")
print("Marks:", marks)
print("Labels:", labels)


Marks: [40 82 60 35 95]
Labels: ['Fail' 'Pass' 'Pass' 'Fail' 'Pass']


#### Handling missing values (NaN)

- In real-world data, we often have missing values represented as np.nan.

In [26]:
arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan])

print("Array:", arr)

# Check which values are NaN
print("Is NaN:", np.isnan(arr))

# Normal mean will give NaN
print("Mean (normal):", arr.mean())

# nanmean ignores NaN values
print("Mean (ignoring NaN):", np.nanmean(arr))


Array: [ 1.  2. nan  4. nan]
Is NaN: [False False  True False  True]
Mean (normal): nan
Mean (ignoring NaN): 2.3333333333333335


In [ ]:
# Replacing NaNs with a value (for example, the mean)

# Compute mean ignoring NaNs
mean_val = np.nanmean(arr)

# Replace NaN with mean_val using np.where
clean_arr = np.where(np.isnan(arr), mean_val, arr)

print("Mean value used:", mean_val)
print("Cleaned array:", clean_arr)


#### Random shuffling (idea of train-test split)

- In data science, we often shuffle rows before splitting into train/test sets.

In [ ]:
# Create a dummy "dataset" with 10 rows and 2 columns
data = np.arange(20).reshape(10, 2)
print("Original data:\n", data)

# -------------------------- not as important
# Generate a random permutation of row indices
np.random.seed(0)
perm = np.random.permutation(len(data))
print("\nRandom permutation of indices:", perm)

# Apply permutation to shuffle data
shuffled = data[perm]
print("\nShuffled data:\n", shuffled)

# -----------------------------------


# Example idea: first 7 rows for training, last 3 for testing
train = shuffled[:7] # start to 7
test  = shuffled[7:] # 7 to end
print("\nTrain data:\n", train)
print("\nTest data:\n", test)


Original data:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

Random permutation of indices: [2 8 4 9 1 6 7 3 0 5]

Shuffled data:
 [[ 4  5]
 [16 17]
 [ 8  9]
 [18 19]
 [ 2  3]
 [12 13]
 [14 15]
 [ 6  7]
 [ 0  1]
 [10 11]]

Train data:
 [[ 4  5]
 [16 17]
 [ 8  9]
 [18 19]
 [ 2  3]
 [12 13]
 [14 15]]

Test data:
 [[ 6  7]
 [ 0  1]
 [10 11]]


### Exerxises

Exercise 1 (arrays & shape)

- Create a 1D array from 1 to 15.
 
- Reshape it into a 3x5 matrix.

- Print:
    -   The matrix

    -  The shape
  
    -   The second row
   
    -   The last column

Exercise 2 (filtering & mean)

- Given ages: [12, 17, 19, 24, 15, 30]

    - Create a NumPy array.

    - Select ages 18 and above.

    - Find the mean age of that filtered group.

<div style="background-color: lightblue; color: white; padding: 10px; text-align: center;">
    <h1>_________________________________END________________________________
</h1> </div>

In [ ]:
import numpy as np

arr = np.arange(1, 16)          # 1 to 15
mat = arr.reshape(3, 5)         # 3x5

print("Matrix:\n", mat)
print("Shape:", mat.shape)
print("Second row:", mat[1, :])
print("Last column:", mat[:, -1])


In [ ]:
ages = np.array([12, 17, 19, 24, 15, 30])

adults = ages[ages >= 18]
print("Adult ages:", adults)
print("Mean adult age:", adults.mean())


<div class="alert alert-block alert-warning">
    <b><font size="5"> Mini Project </font> </b>
</div>

### Analyzing Student Exam Marks with NumPy

We’ll pretend we are data analysts in a school.

- We have marks of 10 students.

- They appeared in 3 subjects: Math, Science, English.

- The game will tell you:
  - We’ll:

    - Create a dataset
    
    - Explore shapes and basic stats
    
    - Find toppers
    
    - Label pass/fail
    
    - Handle “re-evaluation” (improving marks)
    
    - Do some small exercises

<div style="background-color: #002147; color: #fff; padding: 30px; text-align: center;">
    <h1>THANK YOU!
</h1> </div>

<div style="background-color: lightgreen; color: black; padding: 30px;">
    <h4> Mini Project Solutions
        
</h4> </div>

In [ ]:
import numpy as np

# =========================
# Mini Project: Student Marks Analysis
# =========================

# 1) CREATE DATASET
# -----------------
np.random.seed(0)                            # make results repeatable

student_ids = np.arange(1, 11)               # 10 students: IDs 1 to 10
subjects = np.array(["Math", "Science", "English"])

# 10 rows (students) x 3 cols (subjects), marks between 30 and 100
marks = np.random.randint(30, 101, size=(10, 3))

print("=== RAW DATASET ===")
print("Student IDs:", student_ids)
print("Subjects:", subjects)
print("Marks (rows = students, cols = subjects):\n", marks)

# 2) SHAPES AND BASIC STATS
# -------------------------
print("\n=== SHAPES & BASIC STATS ===")
print("Marks.shape:", marks.shape)           # (10, 3)
print("Number of students:", marks.shape[0])
print("Number of subjects:", marks.shape[1])

# Subject-wise mean (axis=0 -> down each column)
subject_means = marks.mean(axis=0)
print("\nAverage marks per subject:")
for i, subj in enumerate(subjects):
    print(f"{subj}: {subject_means[i]:.2f}")

# Student-wise mean (axis=1 -> across each row)
student_means = marks.mean(axis=1)
print("\nAverage marks per student (ID -> avg):")
for sid, avg in zip(student_ids, student_means):
    print(f"Student {sid}: {avg:.2f}")

# Overall stats
print("\nOverall minimum mark:", marks.min())
print("Overall maximum mark:", marks.max())
print("Overall mean mark:", marks.mean())
print("Overall std deviation:", marks.std())

# 3) FIND TOPPERS (TOTAL MARKS)
# -----------------------------
print("\n=== TOPPERS (BY TOTAL MARKS) ===")
total_marks = marks.sum(axis=1)              # sum across subjects
top_index = np.argmax(total_marks)           # index of max total

print("Total marks per student:", total_marks)
print(f"\nTop student ID: {student_ids[top_index]}")
print("Top student's total marks:", total_marks[top_index])

# Sort students by total marks (descending)
sorted_indices = np.argsort(total_marks)[::-1]
print("\nRanking by total marks:")
for idx in sorted_indices:
    print(f"Student {student_ids[idx]} -> Total {total_marks[idx]}")

# 4) LABEL PASS / FAIL
# --------------------
print("\n=== PASS / FAIL (BEFORE RE-EVALUATION) ===")
passing_marks = 40

# True/False per subject
pass_subjectwise = marks >= passing_marks
print("\nPass subject-wise (True = pass, False = fail):\n", pass_subjectwise)

# To pass overall: must pass all 3 subjects
pass_overall = np.all(pass_subjectwise, axis=1)
pass_labels = np.where(pass_overall, "Pass", "Fail")

print("\nOverall result per student:")
for sid, total, label in zip(student_ids, total_marks, pass_labels):
    print(f"Student {sid}: Total = {total}, Result = {label}")

# 5) RE-EVALUATION (GRACE MARKS)
# ------------------------------
print("\n=== RE-EVALUATION: ADD +5 TO EACH SUBJECT FOR FAILED STUDENTS ===")

# Copy original marks so we don't lose them
adjusted_marks = marks.copy()

# Add +5 to all subjects for students who failed overall
adjusted_marks[~pass_overall] = adjusted_marks[~pass_overall] + 5

# Clip values to max 100
adjusted_marks = np.clip(adjusted_marks, 0, 100)

print("\nAdjusted marks after grace (clipped to 100):\n", adjusted_marks)

# Recalculate pass/fail with adjusted marks
pass_subjectwise_new = adjusted_marks >= passing_marks
pass_overall_new = np.all(pass_subjectwise_new, axis=1)
pass_labels_new = np.where(pass_overall_new, "Pass", "Fail")

print("\nOverall result after grace:")
for sid, old_label, new_label in zip(student_ids, pass_labels, pass_labels_new):
    print(f"Student {sid}: {old_label} -> {new_label}")

# 6) SMALL EXERCISES / EXTRA ANALYSIS
# -----------------------------------

# 6a) Best subject for each student
print("\n=== BEST SUBJECT PER STUDENT ===")
best_subject_indices = np.argmax(marks, axis=1)      # index of max mark in each row
for sid, subj_idx in zip(student_ids, best_subject_indices):
    print(f"Student {sid}: Best subject = {subjects[subj_idx]}")

# 6b) Topper per subject
print("\n=== TOPPER(S) PER SUBJECT ===")
for i, subj in enumerate(subjects):
    subj_marks = marks[:, i]                        # marks in this subject
    max_mark = subj_marks.max()
    topper_indices = np.where(subj_marks == max_mark)[0]
    topper_ids = student_ids[topper_indices]
    print(f"\nSubject: {subj}")
    print("Max mark:", max_mark)
    print("Topper student IDs:", topper_ids)

# 6c) Grade bands based on average marks
print("\n=== GRADE BANDS (A/B/C/D) BASED ON AVERAGE ===")
# A: avg >= 80, B: 60-79.99, C: 40-59.99, D: < 40
grades = np.empty_like(student_means, dtype="<U1")   # empty array of strings length 1

grades = np.where(student_means >= 80, "A", grades)
grades = np.where((student_means >= 60) & (student_means < 80), "B", grades)
grades = np.where((student_means >= 40) & (student_means < 60), "C", grades)
grades = np.where(student_means < 40, "D", grades)

print("Student grades:")
for sid, avg, grade in zip(student_ids, student_means, grades):
    print(f"Student {sid}: Avg = {avg:.2f}, Grade = {grade}")

print("\nGrade distribution:")
for label in ["A", "B", "C", "D"]:
    count = np.sum(grades == label)
    print(f"Grade {label}: {count} student(s)")
