- Collections of numbers

- data types, sequence data types: 
    - LIST - 


    

In [ ]:
#       0   1   2   3   4
num1 = [1,  2,  3,  4,  5]

num2 = [10,20,30,40,50]

In [8]:
#       0   1   2   3   4
num1 = [1,  2,  3,  4,  5]

num1[2]


3

In [17]:
num2D = [[1,  2,  3,  4,  5],
         [1,  2,  3] ]



In [18]:
num2D[1] [1]

num2D[1] [2]

3

In [48]:
import numpy as np


arr1D = np.array([1,  2,  3,  4,  5])

In [ ]:
# arrays - attribute
arr1D.ndim  # what are the dimensions of the array

arr1D.shape  # Rows , no columns



(5,)

- attribute - only accessing information - do not need to pass arguments
- method - that takes an input - ( ) are mustttttt

- Arrays are better to represent matrices than lists
    1. only same dimension rows are allowed like in matrices. Shape should be consistent. 
    2. Broadcasting 

In [28]:
arr2D = np.array([[1,   2,   3,   4,    5],
                  [10,  20,  30,  40,  50] ])

arr2D.shape

(2, 5)

In [36]:
arr2D.ndim  # attribute


arr3D = np.array([

    [[1,   2,   3,   4,    5],[10,  20,  30,  40,  50]], # 1
    [[1,   2,   3,   4,    5],[10,  20,  30,  40,  50]], # 2
    [[1,   2,   3,   4,    5],[10,  20,  30,  40,  50]], # 3
    [[1,   2,   3,   4,    5],[10,  20,  30,  40,  50]]  # 4
    
    ])

arr3D.ndim

arr3D.shape

(4, 2, 5)

In [ ]:
num1

num2

num1 + num2 # just concatenatesssss

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [49]:
print("array 1D\n", arr1D)
print("---------------")
print("array 2D\n", arr2D)

array 1D
 [1 2 3 4 5]
---------------
array 2D
 [[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [50]:
arr1D * arr2D

array([[  1,   4,   9,  16,  25],
       [ 10,  40,  90, 160, 250]])

In [ ]:
arr1D @ arr2D # matrix multiplication
# only then 2 matrices can be multiplied!!!

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 5)